<?php

namespace Proxies\__CG__\SeekerPlus\BannerBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class BannerClient extends \SeekerPlus\BannerBundle\Entity\BannerClient implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', '' . "\0" . 'SeekerPlus\\BannerBundle\\Entity\\BannerClient' . "\0" . 'id', '' . "\0" . 'SeekerPlus\\BannerBundle\\Entity\\BannerClient' . "\0" . 'name', '' . "\0" . 'SeekerPlus\\BannerBundle\\Entity\\BannerClient' . "\0" . 'contact', '' . "\0" . 'SeekerPlus\\BannerBundle\\Entity\\BannerClient' . "\0" . 'email', '' . "\0" . 'SeekerPlus\\BannerBundle\\Entity\\BannerClient' . "\0" . 'extrainfo', '' . "\0" . 'SeekerPlus\\BannerBundle\\Entity\\BannerClient' . "\0" . 'state', '' . "\0" . 'SeekerPlus\\BannerBundle\\Entity\\BannerClient' . "\0" . 'checkedOut', '' . "\0" . 'SeekerPlus\\BannerBundle\\Entity\\BannerClient' . "\0" . 'checkedOutTime', '' . "\0" . 'SeekerPlus\\BannerBundle\\Entity\\BannerClient' . "\0" . 'metakey', '' . "\0" . 'SeekerPlus\\BannerBundle\\Entity\\BannerClient' . "\0" . 'ownPrefix', '' . "\0" . 'SeekerPlus\\BannerBundle\\Entity\\BannerClient' . "\0" . 'metakeyPrefix', '' . "\0" . 'SeekerPlus\\BannerBundle\\Entity\\BannerClient' . "\0" . 'purchaseType', '' . "\0" . 'SeekerPlus\\BannerBundle\\Entity\\BannerClient' . "\0" . 'trackClicks', '' . "\0" . 'SeekerPlus\\BannerBundle\\Entity\\BannerClient' . "\0" . 'trackImpressions');
        }

        return array('__isInitialized__', '' . "\0" . 'SeekerPlus\\BannerBundle\\Entity\\BannerClient' . "\0" . 'id', '' . "\0" . 'SeekerPlus\\BannerBundle\\Entity\\BannerClient' . "\0" . 'name', '' . "\0" . 'SeekerPlus\\BannerBundle\\Entity\\BannerClient' . "\0" . 'contact', '' . "\0" . 'SeekerPlus\\BannerBundle\\Entity\\BannerClient' . "\0" . 'email', '' . "\0" . 'SeekerPlus\\BannerBundle\\Entity\\BannerClient' . "\0" . 'extrainfo', '' . "\0" . 'SeekerPlus\\BannerBundle\\Entity\\BannerClient' . "\0" . 'state', '' . "\0" . 'SeekerPlus\\BannerBundle\\Entity\\BannerClient' . "\0" . 'checkedOut', '' . "\0" . 'SeekerPlus\\BannerBundle\\Entity\\BannerClient' . "\0" . 'checkedOutTime', '' . "\0" . 'SeekerPlus\\BannerBundle\\Entity\\BannerClient' . "\0" . 'metakey', '' . "\0" . 'SeekerPlus\\BannerBundle\\Entity\\BannerClient' . "\0" . 'ownPrefix', '' . "\0" . 'SeekerPlus\\BannerBundle\\Entity\\BannerClient' . "\0" . 'metakeyPrefix', '' . "\0" . 'SeekerPlus\\BannerBundle\\Entity\\BannerClient' . "\0" . 'purchaseType', '' . "\0" . 'SeekerPlus\\BannerBundle\\Entity\\BannerClient' . "\0" . 'trackClicks', '' . "\0" . 'SeekerPlus\\BannerBundle\\Entity\\BannerClient' . "\0" . 'trackImpressions');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (BannerClient $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', array());

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setName($name)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setName', array($name));

        return parent::setName($name);
    }

    /**
     * {@inheritDoc}
     */
    public function getName()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getName', array());

        return parent::getName();
    }

    /**
     * {@inheritDoc}
     */
    public function setContact($contact)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setContact', array($contact));

        return parent::setContact($contact);
    }

    /**
     * {@inheritDoc}
     */
    public function getContact()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getContact', array());

        return parent::getContact();
    }

    /**
     * {@inheritDoc}
     */
    public function setEmail($email)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEmail', array($email));

        return parent::setEmail($email);
    }

    /**
     * {@inheritDoc}
     */
    public function getEmail()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEmail', array());

        return parent::getEmail();
    }

    /**
     * {@inheritDoc}
     */
    public function setExtrainfo($extrainfo)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setExtrainfo', array($extrainfo));

        return parent::setExtrainfo($extrainfo);
    }

    /**
     * {@inheritDoc}
     */
    public function getExtrainfo()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getExtrainfo', array());

        return parent::getExtrainfo();
    }

    /**
     * {@inheritDoc}
     */
    public function setState($state)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setState', array($state));

        return parent::setState($state);
    }

    /**
     * {@inheritDoc}
     */
    public function getState()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getState', array());

        return parent::getState();
    }

    /**
     * {@inheritDoc}
     */
    public function setCheckedOut($checkedOut)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCheckedOut', array($checkedOut));

        return parent::setCheckedOut($checkedOut);
    }

    /**
     * {@inheritDoc}
     */
    public function getCheckedOut()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCheckedOut', array());

        return parent::getCheckedOut();
    }

    /**
     * {@inheritDoc}
     */
    public function setCheckedOutTime($checkedOutTime)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCheckedOutTime', array($checkedOutTime));

        return parent::setCheckedOutTime($checkedOutTime);
    }

    /**
     * {@inheritDoc}
     */
    public function getCheckedOutTime()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCheckedOutTime', array());

        return parent::getCheckedOutTime();
    }

    /**
     * {@inheritDoc}
     */
    public function setMetakey($metakey)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setMetakey', array($metakey));

        return parent::setMetakey($metakey);
    }

    /**
     * {@inheritDoc}
     */
    public function getMetakey()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMetakey', array());

        return parent::getMetakey();
    }

    /**
     * {@inheritDoc}
     */
    public function setOwnPrefix($ownPrefix)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setOwnPrefix', array($ownPrefix));

        return parent::setOwnPrefix($ownPrefix);
    }

    /**
     * {@inheritDoc}
     */
    public function getOwnPrefix()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getOwnPrefix', array());

        return parent::getOwnPrefix();
    }

    /**
     * {@inheritDoc}
     */
    public function setMetakeyPrefix($metakeyPrefix)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setMetakeyPrefix', array($metakeyPrefix));

        return parent::setMetakeyPrefix($metakeyPrefix);
    }

    /**
     * {@inheritDoc}
     */
    public function getMetakeyPrefix()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMetakeyPrefix', array());

        return parent::getMetakeyPrefix();
    }

    /**
     * {@inheritDoc}
     */
    public function setPurchaseType($purchaseType)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPurchaseType', array($purchaseType));

        return parent::setPurchaseType($purchaseType);
    }

    /**
     * {@inheritDoc}
     */
    public function getPurchaseType()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPurchaseType', array());

        return parent::getPurchaseType();
    }

    /**
     * {@inheritDoc}
     */
    public function setTrackClicks($trackClicks)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTrackClicks', array($trackClicks));

        return parent::setTrackClicks($trackClicks);
    }

    /**
     * {@inheritDoc}
     */
    public function getTrackClicks()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTrackClicks', array());

        return parent::getTrackClicks();
    }

    /**
     * {@inheritDoc}
     */
    public function setTrackImpressions($trackImpressions)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTrackImpressions', array($trackImpressions));

        return parent::setTrackImpressions($trackImpressions);
    }

    /**
     * {@inheritDoc}
     */
    public function getTrackImpressions()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTrackImpressions', array());

        return parent::getTrackImpressions();
    }

}
