SeekerPlus\BannerBundle\Entity\BannerClient:
    type: entity
    table: seeker_banner_clients
    indexes:
        idx_own_prefix:
            columns:
                - own_prefix
        idx_metakey_prefix:
            columns:
                - metakey_prefix
    id:
        id:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            id: true
            generator:
                strategy: IDENTITY
    fields:
        name:
            type: string
            nullable: false
            length: 255
            fixed: false
            comment: ''
            default: ''
        contact:
            type: string
            nullable: false
            length: 255
            fixed: false
            comment: ''
            default: ''
        email:
            type: string
            nullable: false
            length: 255
            fixed: false
            comment: ''
            default: ''
        extrainfo:
            type: text
            nullable: false
            length: null
            fixed: false
            comment: ''
        state:
            type: boolean
            nullable: false
            comment: ''
            default: '0'
        checkedOut:
            type: integer
            nullable: false
            unsigned: true
            comment: ''
            default: '0'
            column: checked_out
        checkedOutTime:
            type: datetime
            nullable: false
            comment: ''
            default: '0000-00-00 00:00:00'
            column: checked_out_time
        metakey:
            type: text
            nullable: false
            length: null
            fixed: false
            comment: ''
        ownPrefix:
            type: boolean
            nullable: false
            comment: ''
            default: '0'
            column: own_prefix
        metakeyPrefix:
            type: string
            nullable: false
            length: 255
            fixed: false
            comment: ''
            default: ''
            column: metakey_prefix
        purchaseType:
            type: boolean
            nullable: false
            comment: ''
            default: '-1'
            column: purchase_type
        trackClicks:
            type: boolean
            nullable: false
            comment: ''
            default: '-1'
            column: track_clicks
        trackImpressions:
            type: boolean
            nullable: false
            comment: ''
            default: '-1'
            column: track_impressions
    lifecycleCallbacks: {  }
